In [29]:
import pandas as pd
import numpy as np
from pathlib import Path

In [30]:
RAW_PATH = Path("../data/raw")

print(RAW_PATH)

..\data\raw

In [31]:
customers = pd.read_csv(RAW_PATH / "olist_customers_dataset.csv")
geolocation = pd.read_csv(RAW_PATH / "olist_geolocation_dataset.csv")
order_items = pd.read_csv(RAW_PATH / "olist_order_items_dataset.csv")
payments = pd.read_csv(RAW_PATH / "olist_order_payments_dataset.csv")
reviews = pd.read_csv(RAW_PATH / "olist_order_reviews_dataset.csv")
orders = pd.read_csv(RAW_PATH / "olist_orders_dataset.csv")
products = pd.read_csv(RAW_PATH / "olist_products_dataset.csv")
sellers = pd.read_csv(RAW_PATH / "olist_sellers_dataset.csv")
translation = pd.read_csv(RAW_PATH / "product_category_name_translation.csv")

In [32]:
tables = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "payments": payments,
    "reviews": reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "translation": translation
}

In [33]:
for name, df in tables.items():
    print(f"{name:15} {df.shape}")

customers       (99441, 5)
geolocation     (1000163, 5)
order_items     (112650, 7)
payments        (103886, 5)
reviews         (99224, 7)
orders          (99441, 8)
products        (32951, 9)
sellers         (3095, 4)
translation     (71, 2)

In [34]:
for name, df in tables.items():
    print("\n" + "=" * 60)
    print(name.upper())
    print("=" * 60)
    print(df.columns.tolist())

============================================================
CUSTOMERS
============================================================
['customer_id', 'customer_unique_id', 'customer_zip_code_prefix', 'customer_city', 'customer_state']

============================================================
GEOLOCATION
============================================================
['geolocation_zip_code_prefix', 'geolocation_lat', 'geolocation_lng', 'geolocation_city', 'geolocation_state']

============================================================
ORDER_ITEMS
============================================================
['order_id', 'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date', 'price', 'freight_value']

============================================================
PAYMENTS
============================================================
['order_id', 'payment_sequential', 'payment_type', 'payment_installments', 'payment_value']

============================================================
REVIEWS
============================================================
['review_id', 'order_id', 'review_score', 'review_comment_title', 'review_comment_message', 'review_creation_date', 'review_answer_timestamp']

============================================================
ORDERS
============================================================
['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date']

============================================================
PRODUCTS
============================================================
['product_id', 'product_category_name', 'product_name_lenght', 'product_description_lenght', 'product_photos_qty', 'product_weight_g', 'product_length_cm', 'product_height_cm', 'product_width_cm']

============================================================
SELLERS
============================================================
['seller_id', 'seller_zip_code_prefix', 'seller_city', 'seller_state']

============================================================
TRANSLATION
============================================================
['product_category_name', 'product_category_name_english']

In [35]:
for name, df in tables.items():
    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)

    print("Rows:", len(df))
    print("Columns:", len(df.columns))
    print("\nData types:")
    print(df.dtypes)

======================================================================
CUSTOMERS
======================================================================
Rows: 99441
Columns: 5

Data types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

======================================================================
GEOLOCATION
======================================================================
Rows: 1000163
Columns: 5

Data types:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                   str
geolocation_state                  str
dtype: object

======================================================================
ORDER_ITEMS
======================================================================
Rows: 112650
Columns: 7

Data types:
order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

======================================================================
PAYMENTS
======================================================================
Rows: 103886
Columns: 5

Data types:
order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

======================================================================
REVIEWS
======================================================================
Rows: 99224
Columns: 7

Data types:
review_id                    str
order_id                     str
review_score               int64
review_comment_title         str
review_comment_message       str
review_creation_date         str
review_answer_timestamp      str
dtype: object

======================================================================
ORDERS
======================================================================
Rows: 99441
Columns: 8

Data types:
order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

======================================================================
PRODUCTS
======================================================================
Rows: 32951
Columns: 9

Data types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

======================================================================
SELLERS
======================================================================
Rows: 3095
Columns: 4

Data types:
seller_id                   str
seller_zip_code_prefix    int64
seller_city                 str
seller_state                str
dtype: object

======================================================================
TRANSLATION
======================================================================
Rows: 71
Columns: 2

Data types:
product_category_name            str
product_category_name_english    str
dtype: object

In [36]:
for name, df in tables.items():
    missing = pd.DataFrame({
        "MISSING_COUNT": df.isna().sum(),
        "MISSING_PERCENT": (df.isna().mean() * 100).round(2)
    })

    missing = missing[missing["MISSING_COUNT"] > 0]

    print("\n" + "=" * 70)
    print(name.upper())
    print("=" * 70)
    print(missing)

======================================================================
CUSTOMERS
======================================================================
Empty DataFrame
Columns: [MISSING_COUNT, MISSING_PERCENT]
Index: []

======================================================================
GEOLOCATION
======================================================================
Empty DataFrame
Columns: [MISSING_COUNT, MISSING_PERCENT]
Index: []

======================================================================
ORDER_ITEMS
======================================================================
Empty DataFrame
Columns: [MISSING_COUNT, MISSING_PERCENT]
Index: []

======================================================================
PAYMENTS
======================================================================
Empty DataFrame
Columns: [MISSING_COUNT, MISSING_PERCENT]
Index: []

======================================================================
REVIEWS
======================================================================
                        MISSING_COUNT  MISSING_PERCENT
review_comment_title            87656            88.34
review_comment_message          58247            58.70

======================================================================
ORDERS
======================================================================
                               MISSING_COUNT  MISSING_PERCENT
order_approved_at                        160             0.16
order_delivered_carrier_date            1783             1.79
order_delivered_customer_date           2965             2.98

======================================================================
PRODUCTS
======================================================================
                            MISSING_COUNT  MISSING_PERCENT
product_category_name                 610             1.85
product_name_lenght                   610             1.85
product_description_lenght            610             1.85
product_photos_qty                    610             1.85
product_weight_g                        2             0.01
product_length_cm                       2             0.01
product_height_cm                       2             0.01
product_width_cm                        2             0.01

======================================================================
SELLERS
======================================================================
Empty DataFrame
Columns: [MISSING_COUNT, MISSING_PERCENT]
Index: []

======================================================================
TRANSLATION
======================================================================
Empty DataFrame
Columns: [MISSING_COUNT, MISSING_PERCENT]
Index: []

In [37]:
for name, df in tables.items():
    print(
        f"{name:15} "
        f"Duplicate rows: {df.duplicated().sum():,}"
    )

customers       Duplicate rows: 0
geolocation     Duplicate rows: 261,831
order_items     Duplicate rows: 0
payments        Duplicate rows: 0
reviews         Duplicate rows: 0
orders          Duplicate rows: 0
products        Duplicate rows: 0
sellers         Duplicate rows: 0
translation     Duplicate rows: 0

In [38]:
print("customer_id duplicates:",
      customers["customer_id"].duplicated().sum())

print("customer_unique_id duplicates:",
      customers["customer_unique_id"].duplicated().sum())

customer_id duplicates: 0
customer_unique_id duplicates: 3345

In [39]:
print("order_id duplicates:",
      orders["order_id"].duplicated().sum())

order_id duplicates: 0

In [40]:
print("order_id duplicates:",
      order_items["order_id"].duplicated().sum())

print("order_item_id duplicates:",
      order_items["order_item_id"].duplicated().sum())

print(
    "Duplicate order_id + order_item_id:",
    order_items.duplicated(
        subset=["order_id", "order_item_id"]
    ).sum()
)

order_id duplicates: 13984
order_item_id duplicates: 112629
Duplicate order_id + order_item_id: 0

In [41]:
print(
    "Duplicate order_id + payment_sequential:",
    payments.duplicated(
        subset=["order_id", "payment_sequential"]
    ).sum()
)

Duplicate order_id + payment_sequential: 0

In [42]:
print(
    "product_id duplicates:",
    products["product_id"].duplicated().sum()
)

product_id duplicates: 0

In [43]:
print(
    "seller_id duplicates:",
    sellers["seller_id"].duplicated().sum()
)

seller_id duplicates: 0

In [44]:
print(
    "review_id duplicates:",
    reviews["review_id"].duplicated().sum()
)

review_id duplicates: 814

In [45]:
print(
    "product_category_name duplicates:",
    translation["product_category_name"].duplicated().sum()
)

product_category_name duplicates: 0

In [46]:
# CUSTOMERS
# customer_id → ORDERS.customer_id

# ORDERS
# order_id → ORDER_ITEMS.order_id
# order_id → PAYMENTS.order_id
# order_id → REVIEWS.order_id

# ORDER_ITEMS
# product_id → PRODUCTS.product_id
# seller_id → SELLERS.seller_id

# PRODUCTS
# product_category_name → TRANSLATION.product_category_name

# GEOLOCATION
# customer_zip_code_prefix → GEOLOCATION.geolocation_zip_code_prefix
# seller_zip_code_prefix → GEOLOCATION.geolocation_zip_code_prefix

In [47]:
print(
    "Orders with customer_id not found in customers:",
    (~orders["customer_id"].isin(customers["customer_id"])).sum()
)

Orders with customer_id not found in customers: 0

In [48]:
print(
    "Order items with missing order_id match:",
    (~order_items["order_id"].isin(orders["order_id"])).sum()
)

Order items with missing order_id match: 0

In [49]:
print(
    "Order items with missing product match:",
    (~order_items["product_id"].isin(products["product_id"])).sum()
)

Order items with missing product match: 0

In [50]:
print(
    "Order items with missing seller match:",
    (~order_items["seller_id"].isin(sellers["seller_id"])).sum()
)

Order items with missing seller match: 0

In [51]:
print(
    "Payments with missing order match:",
    (~payments["order_id"].isin(orders["order_id"])).sum()
)

Payments with missing order match: 0

In [52]:
print(
    "Reviews with missing order match:",
    (~reviews["order_id"].isin(orders["order_id"])).sum()
)

Reviews with missing order match: 0

In [53]:
orders.columns.tolist()

['order_id',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_approved_at',
 'order_delivered_carrier_date',
 'order_delivered_customer_date',
 'order_estimated_delivery_date']

In [54]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

In [55]:
for col in date_columns:
    orders[col] = pd.to_datetime(orders[col], errors="coerce")

In [57]:
orders[date_columns].describe()

,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99281,97658,96476,99441
mean,2017-12-31 08:43:12.776581,2017-12-31 18:35:24.098800,2018-01-04 21:49:48.138278,2018-01-14 12:09:19.035542,2018-01-24 03:08:37.730111
min,2016-09-04 21:15:19,2016-09-15 12:16:38,2016-10-08 10:34:01,2016-10-11 13:46:32,2016-09-30 00:00:00
25%,2017-09-12 14:46:19,2017-09-12 23:24:16,2017-09-15 22:28:50.250000,2017-09-25 22:07:22.250000,2017-10-03 00:00:00
50%,2018-01-18 23:04:36,2018-01-19 11:36:13,2018-01-24 16:10:58,2018-02-02 19:28:10.500000,2018-02-15 00:00:00
75%,2018-05-04 15:42:16,2018-05-04 20:35:10,2018-05-08 13:37:45,2018-05-15 22:48:52.250000,2018-05-25 00:00:00
max,2018-10-17 17:30:18,2018-09-03 17:40:06,2018-09-11 19:48:28,2018-10-17 13:22:46,2018-11-12 00:00:00

In [58]:
for col in date_columns:
    print(
        col,
        "->",
        orders[col].min(),
        "to",
        orders[col].max()
    )

order_purchase_timestamp -> 2016-09-04 21:15:19 to 2018-10-17 17:30:18
order_approved_at -> 2016-09-15 12:16:38 to 2018-09-03 17:40:06
order_delivered_carrier_date -> 2016-10-08 10:34:01 to 2018-09-11 19:48:28
order_delivered_customer_date -> 2016-10-11 13:46:32 to 2018-10-17 13:22:46
order_estimated_delivery_date -> 2016-09-30 00:00:00 to 2018-11-12 00:00:00

In [59]:
orders["order_status"].value_counts(dropna=False)

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [60]:
orders[
    orders["order_status"].isin(["canceled", "unavailable"])
]["order_status"].value_counts()

order_status
canceled       625
unavailable    609
Name: count, dtype: int64

In [61]:
status_summary = (
    orders["order_status"]
    .value_counts()
    .rename_axis("ORDER_STATUS")
    .reset_index(name="ORDER_COUNT")
)

status_summary["PERCENT"] = (
    status_summary["ORDER_COUNT"]
    / len(orders)
    * 100
).round(2)

status_summary

  ORDER_STATUS  ORDER_COUNT  PERCENT
0    delivered        96478    97.02
1      shipped         1107     1.11
2     canceled          625     0.63
3  unavailable          609     0.61
4     invoiced          314     0.32
5   processing          301     0.30
6      created            5     0.01
7     approved            2     0.00

In [62]:
orders["customer_id"].isna().sum()

np.int64(0)

In [63]:
orders[
    orders["customer_id"].isna()
]

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date]
Index: []

In [64]:
customers.isna().sum()

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

In [65]:
categorical_columns = {
    "orders": ["order_status"],
    "payments": ["payment_type"],
    "reviews": ["review_score"],
    "products": ["product_category_name"],
    "sellers": ["seller_state"],
    "customers": ["customer_state"]
}

In [66]:
for table_name, columns in categorical_columns.items():
    df = tables[table_name]

    print("\n" + "=" * 60)
    print(table_name.upper())
    print("=" * 60)

    for col in columns:
        print(f"\n{col}")
        print(df[col].value_counts(dropna=False).head(20))

============================================================
ORDERS
============================================================

order_status
order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

============================================================
PAYMENTS
============================================================

payment_type
payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: int64

============================================================
REVIEWS
============================================================

review_score
review_score
5    57328
4    19142
1    11424
3     8179
2     3151
Name: count, dtype: int64

============================================================
PRODUCTS
============================================================

product_category_name
product_category_name
cama_mesa_banho                      3029
esporte_lazer                        2867
moveis_decoracao                     2657
beleza_saude                         2444
utilidades_domesticas                2335
automotivo                           1900
informatica_acessorios               1639
brinquedos                           1411
relogios_presentes                   1329
telefonia                            1134
bebes                                 919
perfumaria                            868
papelaria                             849
fashion_bolsas_e_acessorios           849
cool_stuff                            789
ferramentas_jardim                    753
pet_shop                              719
NaN                                   610
eletronicos                           517
construcao_ferramentas_construcao     400
Name: count, dtype: int64

============================================================
SELLERS
============================================================

seller_state
seller_state
SP    1849
PR     349
MG     244
SC     190
RJ     171
RS     129
GO      40
DF      30
ES      23
BA      19
CE      13
PE       9
PB       6
RN       5
MS       5
MT       4
RO       2
SE       2
AC       1
PI       1
Name: count, dtype: int64

============================================================
CUSTOMERS
============================================================

customer_state
customer_state
SP    41746
RJ    12852
MG    11635
RS     5466
PR     5045
SC     3637
BA     3380
DF     2140
ES     2033
GO     2020
PE     1652
CE     1336
PA      975
MT      907
MA      747
MS      715
PB      536
PI      495
RN      485
AL      413
Name: count, dtype: int64

In [68]:
dictionary_parts = []

for table_name, df in tables.items():
    temp = pd.DataFrame({
        "TABLE": table_name,
        "COLUMN": df.columns,
        "DATATYPE": df.dtypes.astype(str).values,
        "MISSING_COUNT": df.isna().sum().values,
        "MISSING_PERCENT": (
            df.isna().mean().values * 100
        ).round(2)
    })

    dictionary_parts.append(temp)

data_dictionary = pd.concat(
    dictionary_parts,
    ignore_index=True
)

data_dictionary.head()

,TABLE,COLUMN,DATATYPE,MISSING_COUNT,MISSING_PERCENT
0,customers,customer_id,str,0,0.0
1,customers,customer_unique_id,str,0,0.0
2,customers,customer_zip_code_prefix,int64,0,0.0
3,customers,customer_city,str,0,0.0
4,customers,customer_state,str,0,0.0

In [69]:
data_dictionary.shape

(52, 5)

In [70]:
from pathlib import Path

Path("../data/processed").mkdir(
    parents=True,
    exist_ok=True
)

In [71]:
data_dictionary.to_csv(
    "../data/processed/data_dictionary.csv",
    index=False
)